# SPDX-License-Identifier: GPL-2.0-or-later

#add by changxue.fang for ramdump get sw version,20201224,start
subdir-ccflags-y += -DHMD_SW_VERSION=\"$(HMD_SW_VERSION)\"
#add by changxue.fang for ramdump get sw version,20201224,end
obj-$(CONFIG_SUPPORT_CRASH_REASON) += kernel_crash.o
